# RegExp for matching basic emoticons
# generated by gemoji-parser

/((?<=^|\s)(?:>:\-?\(|:\-?\)|:'\(|:\-?\\|:\-?\/|:\-?\(|:\-?\*|:\-?\||:o\)|:\-?o|=\-?\)|:\-?D|:\-?p|:\-?P|:\-?b|;\-?p|;\-?P|;\-?b|;\-?\))(?=$|\s))/
