name: Cheatsheet
identifier: com.pilotmoon.popclip.extension.cheatsheet
description: Create a new Cheatsheet note with the selected text.
keywords: notes
popclipVersion: 4069
icon: cheatsheet.svg
app:
  name: Cheatsheet
  link: https://overdesigned.net/cheatsheet/
  bundleIdentifiers: [maccatalyst.com.overdesigned.Cheatsheet]
  checkInstalled: true
requirements: [text]
url: cheatsheet://add?text={popclip text}
