#!/bin/zsh
set -e
module=notion
npx tsc
npx browserify --external axios --standalone foo $module.js > $module.bundle.js
lzfse -encode -i $module.bundle.js > $module.bundle.js.lzfse   
rm $module.bundle.js