#!/bin/zsh
npx tsc
module=slack
npx browserify --ignore canvas --external --external axios --standalone foo $module.js > $module.bundle.js
lzfse -encode -i $module.bundle.js > $module.bundle.js.lzfse   
# rm $module.bundle.js