name: Alfred
identifier: com.pilotmoon.popclip.extension.alfred
description: Activate Alfred with the selected text.
popclip version: 4151
icon: bowler.png
app:
  name: Alfred
  link: "https://www.alfredapp.com"
  bundleIdentifier: com.runningwithcrayons.Alfred
  checkInstalled: true
applescript: 'tell application id "com.runningwithcrayons.Alfred" to search "{popclip text}"'
