name: Mapy
identifier: com.pilotmoon.popclip.extension.mapy
description: Search Mapy.com
icon: Mapy.svg
popclip version: 5155
url: https://mapy.com/turisticka?q=***
app:
  name: Mapy.com
  link: https://mapy.com/
