#!/bin/zsh
curl 'https://api-free.deepl.com/v2/languages?type=target' \
  -H 'Authorization: DeepL-Auth-Key xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:fx' \
  | jq '{langs: map(del(.supports_formality))}' \
  > langs.json
