name: Test Scpt
after: show-result
options: 
- identifier: aaa
  type: string
  label: String Param
  defaultValue: abc123
- identifier: bbB
  type: boolean
  label: Boolean Param
  defaultValue: true
actions:
- title: scpt
  applescript call:
    file: Test.scpt  
    handler: oi
    parameters: [text, option bbB]
- title: scpt2
  applescript file: Test.scpt  
  applescript call:    
    handler: oi
    parameters: [text, option bbB]
- title: pre
  applescript: return "hello from text with no params"
- title: params
  applescript: return "hello from text with params ({popclip app name})"
- title: handler text
  applescript: |
    on go(param,param2)
      return "yes! " & param2
    end go
  applescript call:    
    handler: go
    parameters: [text, option bbB]