#!/bin/zsh
#
# This is inspired by the Drafts Script Reference:
# https://github.com/agiletortoise/drafts-script-reference/
# Hat-tip to Agile Tortoise.
#

# all the config is in tsconfig.json
# npx typedoc

# live mode:
npx typedoc --watch